// PATH: server/src/config/rules.js
// Default WAF rules loaded into DB on first run via seed.js

const DEFAULT_RULES = [
    {
        ruleId: '001',
        name: 'SQL Injection Blocker',
        description: 'Detects UNION, OR 1=1, DROP TABLE patterns',
        category: 'Injection',
        action: 'Block',
        severity: 'Critical',
        patterns: ["'", '--', ';', 'union', 'select', 'drop', 'insert', 'delete', 'exec', 'xp_', '1=1', 'or 1'],
        hits: 4821,
        enabled: true,
    },
    {
        ruleId: '002',
        name: 'XSS Filter',
        description: 'Sanitises <script>, on* handlers, data: URIs',
        category: 'XSS',
        action: 'Block',
        severity: 'High',
        patterns: ['<script', 'onerror=', 'onload=', 'javascript:', '<img', 'alert(', 'document.cookie'],
        hits: 3240,
        enabled: true,
    },
    {
        ruleId: '003',
        name: 'Path Traversal Guard',
        description: 'Blocks ../ and /etc/passwd sequences',
        category: 'LFI/RFI',
        action: 'Block',
        severity: 'High',
        patterns: ['../', '..\\', '/etc/passwd', '/etc/shadow', 'win.ini', 'boot.ini'],
        hits: 2180,
        enabled: true,
    },
    {
        ruleId: '004',
        name: 'Command Injection Shield',
        description: 'Detects shell meta-chars: ;, |, &&, backtick',
        category: 'Injection',
        action: 'Block',
        severity: 'Critical',
        patterns: ['; cat', '| nc', '&& rm', '`id`', '$(', 'wget ', 'curl '],
        hits: 1540,
        enabled: true,
    },
    {
        ruleId: '005',
        name: 'Brute Force Rate Limiter',
        description: 'Limits >10 auth attempts/min per IP',
        category: 'Auth',
        action: 'Block',
        severity: 'Medium',
        patterns: [],
        hits: 980,
        enabled: true,
    },
    {
        ruleId: '006',
        name: 'SSRF Blocker',
        description: 'Blocks requests to 169.254.x, 10.x metadata',
        category: 'SSRF',
        action: 'Block',
        severity: 'Critical',
        patterns: ['169.254.169.254', 'metadata', '192.168.', '10.0.0.', 'localhost', '127.0.0.1'],
        hits: 620,
        enabled: true,
    },
    {
        ruleId: '007',
        name: 'XXE Injection Prevention',
        description: 'Strips ENTITY declarations from XML bodies',
        category: 'XXE',
        action: 'Block',
        severity: 'High',
        patterns: ['<!entity', 'system "', '<!doctype', 'SYSTEM "file'],
        hits: 412,
        enabled: true,
    },
    {
        ruleId: '008',
        name: 'CSRF Token Validator',
        description: 'Enforces SameSite cookies + CSRF token',
        category: 'CSRF',
        action: 'Monitor',
        severity: 'Medium',
        patterns: [],
        hits: 286,
        enabled: false,
    },
]

module.exports = { DEFAULT_RULES }